name: Release package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        if: github.repository == 'socialpoint-labs/spine-json-lib'
        uses: relekang/python-semantic-release@master
        with:
          pypi_username: __token__
          pypi_password: ${{ secrets.pypi_password }}
          github_token: ${{ secrets.GITHUB_TOKEN }}